# Generated by Django 3.1.2 on 2020-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fes_hp_sp_scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=10, null=True)),
                ('pv_all_sp', models.IntegerField(null=True)),
                ('pv_top_sp', models.IntegerField(null=True)),
                ('pv_coupon_sp', models.IntegerField(null=True)),
                ('cvr_sp', models.CharField(max_length=10, null=True)),
                ('tell_sp', models.IntegerField(null=True)),
                ('reserve_sp', models.IntegerField(null=True)),
                ('reserve_hp', models.IntegerField(null=True)),
                ('reserve_homepage', models.IntegerField(null=True)),
                ('day_over_day_changes', models.IntegerField(null=True)),
            ],
        ),
    ]
