# Generated by Django 3.1.2 on 2020-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fes_hp_sp_scrape',
            name='month_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
