# Generated by Django 3.1.2 on 2020-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fes_tb_sp_scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=10, null=True)),
                ('top1', models.IntegerField(null=True)),
                ('photo', models.IntegerField(null=True)),
                ('photo_info', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('menu', models.IntegerField(null=True)),
                ('map', models.IntegerField(null=True)),
                ('coupon', models.IntegerField(null=True)),
                ('p_coupon', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
