# Generated by Django 3.1.2 on 2020-10-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_fes_tb_sp_scrape'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fes_tb_sp_scrape',
            old_name='top1',
            new_name='top',
        ),
    ]
