# Generated by Django 3.1.2 on 2020-10-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_fes_hp_sp_scrape_month_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fes_hp_sp_scrape',
            name='month_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
