# Generated by Django 3.1.7 on 2021-03-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_grg_gn_sp_scrape_grg_hp_sp_scrape_grg_tb_sp_scrape_toro_gn_sp_scrape_toro_hp_sp_scrape_toro_tb_sp_sc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wananakame_gn_sp_scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=10, null=True)),
                ('total', models.IntegerField(null=True)),
                ('top', models.IntegerField(null=True)),
                ('menu', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
                ('photo', models.IntegerField(null=True)),
                ('commitment', models.IntegerField(null=True)),
                ('map', models.IntegerField(null=True)),
                ('coupon', models.IntegerField(null=True)),
                ('reserve', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wananakame_hp_sp_scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=10, null=True)),
                ('pv_all_sp', models.IntegerField(null=True)),
                ('pv_top_sp', models.IntegerField(null=True)),
                ('pv_coupon_sp', models.IntegerField(null=True)),
                ('cvr_sp', models.CharField(max_length=10, null=True)),
                ('tell_sp', models.IntegerField(null=True)),
                ('reserve_sp', models.IntegerField(null=True)),
                ('reserve_hp', models.IntegerField(null=True)),
                ('reserve_homepage', models.IntegerField(null=True)),
                ('day_over_day_changes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wananakame_tb_sp_scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=10, null=True)),
                ('top', models.IntegerField(null=True)),
                ('photo', models.IntegerField(null=True)),
                ('photo_info', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('menu', models.IntegerField(null=True)),
                ('map', models.IntegerField(null=True)),
                ('coupon', models.IntegerField(null=True)),
                ('p_coupon', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
