# Generated by Django 3.1.7 on 2021-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_wananakame_gn_sp_scrape_wananakame_hp_sp_scrape_wananakame_tb_sp_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fes_GMB',
            fields=[
                ('span', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期間')),
                ('total_evaluation', models.FloatField(blank=True, null=True, verbose_name='総合評価')),
                ('total_search', models.IntegerField(blank=True, null=True, verbose_name='合計検索数')),
                ('direct_search', models.IntegerField(blank=True, null=True, verbose_name='直接検索数')),
                ('indirect_search', models.IntegerField(blank=True, null=True, verbose_name='間接検索数')),
                ('total_show', models.IntegerField(blank=True, null=True, verbose_name='合計表示回数')),
                ('via_search_show', models.IntegerField(blank=True, null=True, verbose_name='検索経由の閲覧数')),
                ('via_map_show', models.IntegerField(blank=True, null=True, verbose_name='マップ経由の閲覧数')),
                ('total_action', models.IntegerField(blank=True, null=True, verbose_name='合計反応数')),
                ('access_website', models.IntegerField(blank=True, null=True, verbose_name='ウェブサイトへのアクセス数')),
                ('look_map', models.IntegerField(blank=True, null=True, verbose_name='ルートの照会数')),
                ('call', models.IntegerField(blank=True, null=True, verbose_name='通話数')),
            ],
        ),
        migrations.CreateModel(
            name='Grg_GMB',
            fields=[
                ('span', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期間')),
                ('total_evaluation', models.FloatField(blank=True, null=True, verbose_name='総合評価')),
                ('total_search', models.IntegerField(blank=True, null=True, verbose_name='合計検索数')),
                ('direct_search', models.IntegerField(blank=True, null=True, verbose_name='直接検索数')),
                ('indirect_search', models.IntegerField(blank=True, null=True, verbose_name='間接検索数')),
                ('total_show', models.IntegerField(blank=True, null=True, verbose_name='合計表示回数')),
                ('via_search_show', models.IntegerField(blank=True, null=True, verbose_name='検索経由の閲覧数')),
                ('via_map_show', models.IntegerField(blank=True, null=True, verbose_name='マップ経由の閲覧数')),
                ('total_action', models.IntegerField(blank=True, null=True, verbose_name='合計反応数')),
                ('access_website', models.IntegerField(blank=True, null=True, verbose_name='ウェブサイトへのアクセス数')),
                ('look_map', models.IntegerField(blank=True, null=True, verbose_name='ルートの照会数')),
                ('call', models.IntegerField(blank=True, null=True, verbose_name='通話数')),
            ],
        ),
        migrations.CreateModel(
            name='Toro_GMB',
            fields=[
                ('span', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期間')),
                ('total_evaluation', models.FloatField(blank=True, null=True, verbose_name='総合評価')),
                ('total_search', models.IntegerField(blank=True, null=True, verbose_name='合計検索数')),
                ('direct_search', models.IntegerField(blank=True, null=True, verbose_name='直接検索数')),
                ('indirect_search', models.IntegerField(blank=True, null=True, verbose_name='間接検索数')),
                ('total_show', models.IntegerField(blank=True, null=True, verbose_name='合計表示回数')),
                ('via_search_show', models.IntegerField(blank=True, null=True, verbose_name='検索経由の閲覧数')),
                ('via_map_show', models.IntegerField(blank=True, null=True, verbose_name='マップ経由の閲覧数')),
                ('total_action', models.IntegerField(blank=True, null=True, verbose_name='合計反応数')),
                ('access_website', models.IntegerField(blank=True, null=True, verbose_name='ウェブサイトへのアクセス数')),
                ('look_map', models.IntegerField(blank=True, null=True, verbose_name='ルートの照会数')),
                ('call', models.IntegerField(blank=True, null=True, verbose_name='通話数')),
            ],
        ),
        migrations.CreateModel(
            name='Wanaichi_GMB',
            fields=[
                ('span', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期間')),
                ('total_evaluation', models.FloatField(blank=True, null=True, verbose_name='総合評価')),
                ('total_search', models.IntegerField(blank=True, null=True, verbose_name='合計検索数')),
                ('direct_search', models.IntegerField(blank=True, null=True, verbose_name='直接検索数')),
                ('indirect_search', models.IntegerField(blank=True, null=True, verbose_name='間接検索数')),
                ('total_show', models.IntegerField(blank=True, null=True, verbose_name='合計表示回数')),
                ('via_search_show', models.IntegerField(blank=True, null=True, verbose_name='検索経由の閲覧数')),
                ('via_map_show', models.IntegerField(blank=True, null=True, verbose_name='マップ経由の閲覧数')),
                ('total_action', models.IntegerField(blank=True, null=True, verbose_name='合計反応数')),
                ('access_website', models.IntegerField(blank=True, null=True, verbose_name='ウェブサイトへのアクセス数')),
                ('look_map', models.IntegerField(blank=True, null=True, verbose_name='ルートの照会数')),
                ('call', models.IntegerField(blank=True, null=True, verbose_name='通話数')),
            ],
        ),
        migrations.CreateModel(
            name='Wananakame_GMB',
            fields=[
                ('span', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期間')),
                ('total_evaluation', models.FloatField(blank=True, null=True, verbose_name='総合評価')),
                ('total_search', models.IntegerField(blank=True, null=True, verbose_name='合計検索数')),
                ('direct_search', models.IntegerField(blank=True, null=True, verbose_name='直接検索数')),
                ('indirect_search', models.IntegerField(blank=True, null=True, verbose_name='間接検索数')),
                ('total_show', models.IntegerField(blank=True, null=True, verbose_name='合計表示回数')),
                ('via_search_show', models.IntegerField(blank=True, null=True, verbose_name='検索経由の閲覧数')),
                ('via_map_show', models.IntegerField(blank=True, null=True, verbose_name='マップ経由の閲覧数')),
                ('total_action', models.IntegerField(blank=True, null=True, verbose_name='合計反応数')),
                ('access_website', models.IntegerField(blank=True, null=True, verbose_name='ウェブサイトへのアクセス数')),
                ('look_map', models.IntegerField(blank=True, null=True, verbose_name='ルートの照会数')),
                ('call', models.IntegerField(blank=True, null=True, verbose_name='通話数')),
            ],
        ),
    ]
