# Generated by Django 3.1.7 on 2021-03-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_fes_gmb_grg_gmb_toro_gmb_wanaichi_gmb_wananakame_gmb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fes_gmb',
            options={'verbose_name': 'FES_GMB', 'verbose_name_plural': 'FES_GMB'},
        ),
        migrations.AlterModelOptions(
            name='fes_gn_sp_scrape',
            options={'verbose_name': 'FES_ぐる_SP', 'verbose_name_plural': 'FES_ぐる_SP'},
        ),
        migrations.AlterModelOptions(
            name='fes_hp_sp_scrape',
            options={'verbose_name': 'FES_HP_SP', 'verbose_name_plural': 'FES_HP_SP'},
        ),
        migrations.AlterModelOptions(
            name='fes_tb_sp_scrape',
            options={'verbose_name': 'FES_食べ_SP', 'verbose_name_plural': 'FES_食べ_SP'},
        ),
        migrations.AlterModelOptions(
            name='grg_gmb',
            options={'verbose_name': 'Garage_GMB', 'verbose_name_plural': 'Garage_GMB'},
        ),
        migrations.AlterModelOptions(
            name='grg_gn_sp_scrape',
            options={'verbose_name': 'Garage_ぐる_SP', 'verbose_name_plural': 'Garage_ぐる_SP'},
        ),
        migrations.AlterModelOptions(
            name='grg_hp_sp_scrape',
            options={'verbose_name': 'Garage_HP_SP', 'verbose_name_plural': 'Garage_HP_SP'},
        ),
        migrations.AlterModelOptions(
            name='grg_tb_sp_scrape',
            options={'verbose_name': 'Garage_食べ_SP', 'verbose_name_plural': 'Garage_食べ_SP'},
        ),
        migrations.AlterModelOptions(
            name='toro_gmb',
            options={'verbose_name': '灯篭_GMB', 'verbose_name_plural': '灯篭_GMB'},
        ),
        migrations.AlterModelOptions(
            name='toro_gn_sp_scrape',
            options={'verbose_name': '灯篭_ぐる_SP', 'verbose_name_plural': '灯篭_ぐる_SP'},
        ),
        migrations.AlterModelOptions(
            name='toro_hp_sp_scrape',
            options={'verbose_name': '灯篭_HP_SP', 'verbose_name_plural': '灯篭_HP_SP'},
        ),
        migrations.AlterModelOptions(
            name='toro_tb_sp_scrape',
            options={'verbose_name': '灯篭_食べ_SP', 'verbose_name_plural': '灯篭_食べ_SP'},
        ),
        migrations.AlterModelOptions(
            name='wana_gn_sp_scrape',
            options={'verbose_name': '罠一目_ぐる_SP', 'verbose_name_plural': '罠一目_ぐる_SP'},
        ),
        migrations.AlterModelOptions(
            name='wana_hp_sp_scrape',
            options={'verbose_name': '罠一目_HP_SP', 'verbose_name_plural': '罠一目_HP_SP'},
        ),
        migrations.AlterModelOptions(
            name='wana_tb_sp_scrape',
            options={'verbose_name': '罠一目_食べ_SP', 'verbose_name_plural': '罠一目_食べ_SP'},
        ),
        migrations.AlterModelOptions(
            name='wanaichi_gmb',
            options={'verbose_name': '罠一目_GMB', 'verbose_name_plural': '罠一目_GMB'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_gmb',
            options={'verbose_name': '罠中目黒_GMB', 'verbose_name_plural': '罠中目黒_GMB'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_gn_sp_scrape',
            options={'verbose_name': '罠中目黒_ぐる_SP', 'verbose_name_plural': '罠中目黒_ぐる_SP'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_hp_sp_scrape',
            options={'verbose_name': '罠中目黒_HP_SP', 'verbose_name_plural': '罠中目黒_HP_SP'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_tb_sp_scrape',
            options={'verbose_name': '罠中目黒_食べ_SP', 'verbose_name_plural': '罠中目黒_食べ_SP'},
        ),
        migrations.AddField(
            model_name='toro_gmb',
            name='span_id',
            field=models.CharField(default='0', max_length=20, verbose_name='期間ID'),
        ),
    ]
