# Generated by Django 3.1.7 on 2021-03-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20210309_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='fes_gmb',
            name='span_id',
            field=models.CharField(default='0', max_length=20, verbose_name='期間ID'),
        ),
        migrations.AddField(
            model_name='grg_gmb',
            name='span_id',
            field=models.CharField(default='0', max_length=20, verbose_name='期間ID'),
        ),
        migrations.AddField(
            model_name='wanaichi_gmb',
            name='span_id',
            field=models.CharField(default='0', max_length=20, verbose_name='期間ID'),
        ),
        migrations.AddField(
            model_name='wananakame_gmb',
            name='span_id',
            field=models.CharField(default='0', max_length=20, verbose_name='期間ID'),
        ),
    ]
