# Generated by Django 3.1.7 on 2021-03-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20210312_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fes_gn_sp_scrape',
            new_name='Fes_gn_scrape',
        ),
        migrations.RenameModel(
            old_name='Fes_hp_sp_scrape',
            new_name='Fes_hp_scrape',
        ),
        migrations.RenameModel(
            old_name='Fes_tb_sp_scrape',
            new_name='Fes_tb_scrape',
        ),
        migrations.RenameModel(
            old_name='Grg_gn_sp_scrape',
            new_name='Grg_gn_scrape',
        ),
        migrations.RenameModel(
            old_name='Grg_hp_sp_scrape',
            new_name='Grg_hp_scrape',
        ),
        migrations.RenameModel(
            old_name='Grg_tb_sp_scrape',
            new_name='Grg_tb_scrape',
        ),
        migrations.RenameModel(
            old_name='Toro_gn_sp_scrape',
            new_name='Toro_gn_scrape',
        ),
        migrations.RenameModel(
            old_name='Toro_hp_sp_scrape',
            new_name='Toro_hp_scrape',
        ),
        migrations.RenameModel(
            old_name='Toro_tb_sp_scrape',
            new_name='Toro_tb_scrape',
        ),
        migrations.RenameModel(
            old_name='Wana_gn_sp_scrape',
            new_name='Wana_gn_scrape',
        ),
        migrations.RenameModel(
            old_name='Wana_hp_sp_scrape',
            new_name='Wana_hp_scrape',
        ),
        migrations.RenameModel(
            old_name='Wana_tb_sp_scrape',
            new_name='Wana_tb_scrape',
        ),
        migrations.RenameModel(
            old_name='Wananakame_gn_sp_scrape',
            new_name='Wananakame_gn_scrape',
        ),
        migrations.RenameModel(
            old_name='Wananakame_hp_sp_scrape',
            new_name='Wananakame_hp_scrape',
        ),
        migrations.RenameModel(
            old_name='Wananakame_tb_sp_scrape',
            new_name='Wananakame_tb_scrape',
        ),
    ]
