# Generated by Django 3.1.7 on 2021-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_auto_20210312_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fes_gn_scrape',
            options={'verbose_name': 'FES_ぐる', 'verbose_name_plural': 'FES_ぐる'},
        ),
        migrations.AlterModelOptions(
            name='fes_hp_scrape',
            options={'verbose_name': 'FES_HP', 'verbose_name_plural': 'FES_HP'},
        ),
        migrations.AlterModelOptions(
            name='fes_tb_scrape',
            options={'verbose_name': 'FES_食べ', 'verbose_name_plural': 'FES_食べ'},
        ),
        migrations.AlterModelOptions(
            name='grg_gn_scrape',
            options={'verbose_name': 'Garage_ぐる', 'verbose_name_plural': 'Garage_ぐる'},
        ),
        migrations.AlterModelOptions(
            name='grg_hp_scrape',
            options={'verbose_name': 'Garage_HP', 'verbose_name_plural': 'Garage_HP'},
        ),
        migrations.AlterModelOptions(
            name='grg_tb_scrape',
            options={'verbose_name': 'Garage_食べ', 'verbose_name_plural': 'Garage_食べ'},
        ),
        migrations.AlterModelOptions(
            name='toro_gn_scrape',
            options={'verbose_name': '灯篭_ぐる', 'verbose_name_plural': '灯篭_ぐる'},
        ),
        migrations.AlterModelOptions(
            name='toro_hp_scrape',
            options={'verbose_name': '灯篭_HP', 'verbose_name_plural': '灯篭_HP'},
        ),
        migrations.AlterModelOptions(
            name='toro_tb_scrape',
            options={'verbose_name': '灯篭_食べ', 'verbose_name_plural': '灯篭_食べ'},
        ),
        migrations.AlterModelOptions(
            name='wana_gn_scrape',
            options={'verbose_name': '罠一目_ぐる', 'verbose_name_plural': '罠一目_ぐる'},
        ),
        migrations.AlterModelOptions(
            name='wana_hp_scrape',
            options={'verbose_name': '罠一目_HP', 'verbose_name_plural': '罠一目_HP'},
        ),
        migrations.AlterModelOptions(
            name='wana_tb_scrape',
            options={'verbose_name': '罠一目_食べ', 'verbose_name_plural': '罠一目_食べ'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_gn_scrape',
            options={'verbose_name': '罠中目黒_ぐる', 'verbose_name_plural': '罠中目黒_ぐる'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_hp_scrape',
            options={'verbose_name': '罠中目黒_HP', 'verbose_name_plural': '罠中目黒_HP'},
        ),
        migrations.AlterModelOptions(
            name='wananakame_tb_scrape',
            options={'verbose_name': '罠中目黒_食べ', 'verbose_name_plural': '罠中目黒_食べ'},
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='commitment_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='coupon_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='map_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='menu_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='photo_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='reserve_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='seat_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='top_pv',
        ),
        migrations.RemoveField(
            model_name='fes_gn_scrape',
            name='total_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='commitment_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='coupon_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='map_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='menu_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='photo_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='reserve_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='seat_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='top_pv',
        ),
        migrations.RemoveField(
            model_name='grg_gn_scrape',
            name='total_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='commitment_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='coupon_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='map_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='menu_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='photo_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='reserve_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='seat_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='top_pv',
        ),
        migrations.RemoveField(
            model_name='toro_gn_scrape',
            name='total_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='commitment_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='coupon_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='map_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='menu_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='photo_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='reserve_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='seat_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='top_pv',
        ),
        migrations.RemoveField(
            model_name='wana_gn_scrape',
            name='total_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='commitment_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='coupon_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='map_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='menu_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='photo_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='reserve_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='seat_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='top_pv',
        ),
        migrations.RemoveField(
            model_name='wananakame_gn_scrape',
            name='total_pv',
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='commitment_pv_app',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='commitment_pv_pc',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='commitment_pv_sp',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='coupon_pv_app',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='map_pv_app',
            field=models.IntegerField(null=True, verbose_name='地図PV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='map_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図PV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='menu_pv_app',
            field=models.IntegerField(null=True, verbose_name='メニューPV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='photo_pv_app',
            field=models.IntegerField(null=True, verbose_name='写真PV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='photo_pv_pc',
            field=models.IntegerField(null=True, verbose_name='写真PV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真PV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='reserve_pv_app',
            field=models.IntegerField(null=True, verbose_name='予約PV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='reserve_pv_pc',
            field=models.IntegerField(null=True, verbose_name='予約PV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='reserve_pv_sp',
            field=models.IntegerField(null=True, verbose_name='予約PV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='seat_pv_app',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='top_pv_app',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_SP'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='total_pv_app',
            field=models.IntegerField(null=True, verbose_name='合計PV_app'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_PC'),
        ),
        migrations.AddField(
            model_name='fes_gn_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='commitment_pv_app',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='commitment_pv_pc',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='commitment_pv_sp',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='coupon_pv_app',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='map_pv_app',
            field=models.IntegerField(null=True, verbose_name='地図PV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='map_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図PV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='menu_pv_app',
            field=models.IntegerField(null=True, verbose_name='メニューPV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='photo_pv_app',
            field=models.IntegerField(null=True, verbose_name='写真PV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='photo_pv_pc',
            field=models.IntegerField(null=True, verbose_name='写真PV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真PV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='reserve_pv_app',
            field=models.IntegerField(null=True, verbose_name='予約PV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='reserve_pv_pc',
            field=models.IntegerField(null=True, verbose_name='予約PV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='reserve_pv_sp',
            field=models.IntegerField(null=True, verbose_name='予約PV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='seat_pv_app',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='top_pv_app',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_SP'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='total_pv_app',
            field=models.IntegerField(null=True, verbose_name='合計PV_app'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_PC'),
        ),
        migrations.AddField(
            model_name='grg_gn_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='commitment_pv_app',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='commitment_pv_pc',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='commitment_pv_sp',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='coupon_pv_app',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='map_pv_app',
            field=models.IntegerField(null=True, verbose_name='地図PV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='map_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図PV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='menu_pv_app',
            field=models.IntegerField(null=True, verbose_name='メニューPV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='photo_pv_app',
            field=models.IntegerField(null=True, verbose_name='写真PV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='photo_pv_pc',
            field=models.IntegerField(null=True, verbose_name='写真PV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真PV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='reserve_pv_app',
            field=models.IntegerField(null=True, verbose_name='予約PV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='reserve_pv_pc',
            field=models.IntegerField(null=True, verbose_name='予約PV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='reserve_pv_sp',
            field=models.IntegerField(null=True, verbose_name='予約PV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='seat_pv_app',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='top_pv_app',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_SP'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='total_pv_app',
            field=models.IntegerField(null=True, verbose_name='合計PV_app'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_PC'),
        ),
        migrations.AddField(
            model_name='toro_gn_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='commitment_pv_app',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='commitment_pv_pc',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='commitment_pv_sp',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='coupon_pv_app',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='map_pv_app',
            field=models.IntegerField(null=True, verbose_name='地図PV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='map_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図PV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='menu_pv_app',
            field=models.IntegerField(null=True, verbose_name='メニューPV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='photo_pv_app',
            field=models.IntegerField(null=True, verbose_name='写真PV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='photo_pv_pc',
            field=models.IntegerField(null=True, verbose_name='写真PV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真PV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='reserve_pv_app',
            field=models.IntegerField(null=True, verbose_name='予約PV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='reserve_pv_pc',
            field=models.IntegerField(null=True, verbose_name='予約PV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='reserve_pv_sp',
            field=models.IntegerField(null=True, verbose_name='予約PV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='seat_pv_app',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='top_pv_app',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_SP'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='total_pv_app',
            field=models.IntegerField(null=True, verbose_name='合計PV_app'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_PC'),
        ),
        migrations.AddField(
            model_name='wana_gn_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='commitment_pv_app',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='commitment_pv_pc',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='commitment_pv_sp',
            field=models.IntegerField(null=True, verbose_name='こだわりPV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='coupon_pv_app',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='map_pv_app',
            field=models.IntegerField(null=True, verbose_name='地図PV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='map_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図PV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='menu_pv_app',
            field=models.IntegerField(null=True, verbose_name='メニューPV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='photo_pv_app',
            field=models.IntegerField(null=True, verbose_name='写真PV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='photo_pv_pc',
            field=models.IntegerField(null=True, verbose_name='写真PV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真PV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='reserve_pv_app',
            field=models.IntegerField(null=True, verbose_name='予約PV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='reserve_pv_pc',
            field=models.IntegerField(null=True, verbose_name='予約PV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='reserve_pv_sp',
            field=models.IntegerField(null=True, verbose_name='予約PV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='seat_pv_app',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='席個室貸切PV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='top_pv_app',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_SP'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='total_pv_app',
            field=models.IntegerField(null=True, verbose_name='合計PV_app'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_PC'),
        ),
        migrations.AddField(
            model_name='wananakame_gn_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_SP'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_course_number',
            field=models.IntegerField(null=True, verbose_name='予約_コース_件数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_course_people',
            field=models.IntegerField(null=True, verbose_name='予約_コース_人数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_course_price',
            field=models.IntegerField(null=True, verbose_name='予約_コース_金額'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_request_number',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_件数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_request_people',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_人数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_seatonly_number',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_件数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_seatonly_people',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_人数'),
        ),
        migrations.AlterField(
            model_name='fes_gn_scrape',
            name='reserve_total',
            field=models.IntegerField(null=True, verbose_name='予約_合計件数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_course_number',
            field=models.IntegerField(null=True, verbose_name='予約_コース_件数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_course_people',
            field=models.IntegerField(null=True, verbose_name='予約_コース_人数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_course_price',
            field=models.IntegerField(null=True, verbose_name='予約_コース_金額'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_request_number',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_件数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_request_people',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_人数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_seatonly_number',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_件数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_seatonly_people',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_人数'),
        ),
        migrations.AlterField(
            model_name='grg_gn_scrape',
            name='reserve_total',
            field=models.IntegerField(null=True, verbose_name='予約_合計件数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_course_number',
            field=models.IntegerField(null=True, verbose_name='予約_コース_件数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_course_people',
            field=models.IntegerField(null=True, verbose_name='予約_コース_人数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_course_price',
            field=models.IntegerField(null=True, verbose_name='予約_コース_金額'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_request_number',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_件数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_request_people',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_人数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_seatonly_number',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_件数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_seatonly_people',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_人数'),
        ),
        migrations.AlterField(
            model_name='toro_gn_scrape',
            name='reserve_total',
            field=models.IntegerField(null=True, verbose_name='予約_合計件数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_course_number',
            field=models.IntegerField(null=True, verbose_name='予約_コース_件数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_course_people',
            field=models.IntegerField(null=True, verbose_name='予約_コース_人数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_course_price',
            field=models.IntegerField(null=True, verbose_name='予約_コース_金額'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_request_number',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_件数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_request_people',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_人数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_seatonly_number',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_件数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_seatonly_people',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_人数'),
        ),
        migrations.AlterField(
            model_name='wana_gn_scrape',
            name='reserve_total',
            field=models.IntegerField(null=True, verbose_name='予約_合計件数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_course_number',
            field=models.IntegerField(null=True, verbose_name='予約_コース_件数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_course_people',
            field=models.IntegerField(null=True, verbose_name='予約_コース_人数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_course_price',
            field=models.IntegerField(null=True, verbose_name='予約_コース_金額'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_request_number',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_件数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_request_people',
            field=models.IntegerField(null=True, verbose_name='予約_リクエスト_人数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_seatonly_number',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_件数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_seatonly_people',
            field=models.IntegerField(null=True, verbose_name='予約_席のみ_人数'),
        ),
        migrations.AlterField(
            model_name='wananakame_gn_scrape',
            name='reserve_total',
            field=models.IntegerField(null=True, verbose_name='予約_合計件数'),
        ),
    ]
