# Generated by Django 3.1.7 on 2021-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_auto_20210312_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fes_hp_scrape',
            name='day_over_day_changes',
        ),
        migrations.RemoveField(
            model_name='fes_hp_scrape',
            name='reserve_homepage',
        ),
        migrations.RemoveField(
            model_name='fes_hp_scrape',
            name='reserve_hp',
        ),
        migrations.RemoveField(
            model_name='grg_hp_scrape',
            name='day_over_day_changes',
        ),
        migrations.RemoveField(
            model_name='grg_hp_scrape',
            name='reserve_homepage',
        ),
        migrations.RemoveField(
            model_name='grg_hp_scrape',
            name='reserve_hp',
        ),
        migrations.RemoveField(
            model_name='toro_hp_scrape',
            name='day_over_day_changes',
        ),
        migrations.RemoveField(
            model_name='toro_hp_scrape',
            name='reserve_homepage',
        ),
        migrations.RemoveField(
            model_name='toro_hp_scrape',
            name='reserve_hp',
        ),
        migrations.RemoveField(
            model_name='wana_hp_scrape',
            name='day_over_day_changes',
        ),
        migrations.RemoveField(
            model_name='wana_hp_scrape',
            name='reserve_homepage',
        ),
        migrations.RemoveField(
            model_name='wana_hp_scrape',
            name='reserve_hp',
        ),
        migrations.RemoveField(
            model_name='wananakame_hp_scrape',
            name='day_over_day_changes',
        ),
        migrations.RemoveField(
            model_name='wananakame_hp_scrape',
            name='reserve_homepage',
        ),
        migrations.RemoveField(
            model_name='wananakame_hp_scrape',
            name='reserve_hp',
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='cvr_pc',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='pv_all_pc',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='pv_coupon_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='pv_top_pc',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='reserve_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='fes_hp_scrape',
            name='tell_pc',
            field=models.IntegerField(null=True, verbose_name='電話件数_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='cvr_pc',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='pv_all_pc',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='pv_coupon_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='pv_top_pc',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='reserve_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='grg_hp_scrape',
            name='tell_pc',
            field=models.IntegerField(null=True, verbose_name='電話件数_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='cvr_pc',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='pv_all_pc',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='pv_coupon_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='pv_top_pc',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='reserve_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='toro_hp_scrape',
            name='tell_pc',
            field=models.IntegerField(null=True, verbose_name='電話件数_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='cvr_pc',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='pv_all_pc',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='pv_coupon_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='pv_top_pc',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='reserve_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wana_hp_scrape',
            name='tell_pc',
            field=models.IntegerField(null=True, verbose_name='電話件数_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='cvr_pc',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='pv_all_pc',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='pv_coupon_pc',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='pv_top_pc',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='reserve_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_hp_scrape',
            name='tell_pc',
            field=models.IntegerField(null=True, verbose_name='電話件数_pc'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='cvr_sp',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='pv_all_sp',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='pv_coupon_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='pv_top_sp',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='reserve_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='tell_sp',
            field=models.IntegerField(null=True, verbose_name='電話件数_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='cvr_sp',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='pv_all_sp',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='pv_coupon_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='pv_top_sp',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='reserve_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='tell_sp',
            field=models.IntegerField(null=True, verbose_name='電話件数_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='cvr_sp',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='pv_all_sp',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='pv_coupon_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='pv_top_sp',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='reserve_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='tell_sp',
            field=models.IntegerField(null=True, verbose_name='電話件数_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='cvr_sp',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='pv_all_sp',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='pv_coupon_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='pv_top_sp',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='reserve_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='tell_sp',
            field=models.IntegerField(null=True, verbose_name='電話件数_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='cvr_sp',
            field=models.CharField(max_length=10, null=True, verbose_name='CVR_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='pv_all_sp',
            field=models.IntegerField(null=True, verbose_name='店舗総PV_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='pv_coupon_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンページPV_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='pv_top_sp',
            field=models.IntegerField(null=True, verbose_name='店舗TOP PV_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='reserve_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='tell_sp',
            field=models.IntegerField(null=True, verbose_name='電話件数_sp'),
        ),
    ]
