# Generated by Django 3.1.7 on 2021-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_auto_20210312_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_pc'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_sp'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_pc'),
        ),
        migrations.AlterField(
            model_name='fes_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_pc'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_sp'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_pc'),
        ),
        migrations.AlterField(
            model_name='grg_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_pc'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_sp'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_pc'),
        ),
        migrations.AlterField(
            model_name='toro_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_pc'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_sp'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_pc'),
        ),
        migrations.AlterField(
            model_name='wana_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='reserve_homepage_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_pc'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='reserve_homepage_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホームページ_sp'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='reserve_hp_pc',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_pc'),
        ),
        migrations.AlterField(
            model_name='wananakame_hp_scrape',
            name='reserve_hp_sp',
            field=models.IntegerField(null=True, verbose_name='予約件数_ホットペッパー_sp'),
        ),
    ]
