# Generated by Django 3.1.7 on 2021-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_auto_20210312_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='map',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='other',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='p_coupon',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='photo_info',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='top',
        ),
        migrations.RemoveField(
            model_name='fes_tb_scrape',
            name='total',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='map',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='other',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='p_coupon',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='photo_info',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='top',
        ),
        migrations.RemoveField(
            model_name='grg_tb_scrape',
            name='total',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='map',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='other',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='p_coupon',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='photo_info',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='top',
        ),
        migrations.RemoveField(
            model_name='toro_tb_scrape',
            name='total',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='map',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='other',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='p_coupon',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='photo_info',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='top',
        ),
        migrations.RemoveField(
            model_name='wana_tb_scrape',
            name='total',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='map',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='other',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='p_coupon',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='photo_info',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='top',
        ),
        migrations.RemoveField(
            model_name='wananakame_tb_scrape',
            name='total',
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='map_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図_クーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='net_reserve',
            field=models.IntegerField(null=True, verbose_name='ネット予約'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='other_pv_pc',
            field=models.IntegerField(null=True, verbose_name='その他PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='other_pv_sp',
            field=models.IntegerField(null=True, verbose_name='その他PV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='p_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='p_coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_drink_pv_pc',
            field=models.IntegerField(null=True, verbose_name='ドリンク写真_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_exterior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='外観写真_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_food_pv_pc',
            field=models.IntegerField(null=True, verbose_name='料理写真PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_info_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真詳細PV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_interior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='内観写真_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真一覧PV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='rating_pv_pc',
            field=models.IntegerField(null=True, verbose_name='口コミPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='rating_pv_sp',
            field=models.IntegerField(null=True, verbose_name='口コミPV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_sp'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_pc'),
        ),
        migrations.AddField(
            model_name='fes_tb_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='map_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図_クーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='net_reserve',
            field=models.IntegerField(null=True, verbose_name='ネット予約'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='other_pv_pc',
            field=models.IntegerField(null=True, verbose_name='その他PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='other_pv_sp',
            field=models.IntegerField(null=True, verbose_name='その他PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='p_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='p_coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_drink_pv_pc',
            field=models.IntegerField(null=True, verbose_name='ドリンク写真_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_exterior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='外観写真_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_food_pv_pc',
            field=models.IntegerField(null=True, verbose_name='料理写真PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_info_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真詳細PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_interior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='内観写真_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真一覧PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='rating_pv_pc',
            field=models.IntegerField(null=True, verbose_name='口コミPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='rating_pv_sp',
            field=models.IntegerField(null=True, verbose_name='口コミPV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_sp'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_pc'),
        ),
        migrations.AddField(
            model_name='grg_tb_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='map_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図_クーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='net_reserve',
            field=models.IntegerField(null=True, verbose_name='ネット予約'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='other_pv_pc',
            field=models.IntegerField(null=True, verbose_name='その他PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='other_pv_sp',
            field=models.IntegerField(null=True, verbose_name='その他PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='p_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='p_coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_drink_pv_pc',
            field=models.IntegerField(null=True, verbose_name='ドリンク写真_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_exterior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='外観写真_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_food_pv_pc',
            field=models.IntegerField(null=True, verbose_name='料理写真PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_info_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真詳細PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_interior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='内観写真_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真一覧PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='rating_pv_pc',
            field=models.IntegerField(null=True, verbose_name='口コミPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='rating_pv_sp',
            field=models.IntegerField(null=True, verbose_name='口コミPV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_sp'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_pc'),
        ),
        migrations.AddField(
            model_name='toro_tb_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='map_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図_クーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='net_reserve',
            field=models.IntegerField(null=True, verbose_name='ネット予約'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='other_pv_pc',
            field=models.IntegerField(null=True, verbose_name='その他PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='other_pv_sp',
            field=models.IntegerField(null=True, verbose_name='その他PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='p_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='p_coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_drink_pv_pc',
            field=models.IntegerField(null=True, verbose_name='ドリンク写真_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_exterior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='外観写真_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_food_pv_pc',
            field=models.IntegerField(null=True, verbose_name='料理写真PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_info_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真詳細PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_interior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='内観写真_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真一覧PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='rating_pv_pc',
            field=models.IntegerField(null=True, verbose_name='口コミPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='rating_pv_sp',
            field=models.IntegerField(null=True, verbose_name='口コミPV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_sp'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_pc'),
        ),
        migrations.AddField(
            model_name='wana_tb_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='クーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='map_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='地図_クーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='map_pv_sp',
            field=models.IntegerField(null=True, verbose_name='地図PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='menu_pv_pc',
            field=models.IntegerField(null=True, verbose_name='メニューPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='menu_pv_sp',
            field=models.IntegerField(null=True, verbose_name='メニューPV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='net_reserve',
            field=models.IntegerField(null=True, verbose_name='ネット予約'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='other_pv_pc',
            field=models.IntegerField(null=True, verbose_name='その他PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='other_pv_sp',
            field=models.IntegerField(null=True, verbose_name='その他PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='p_coupon_pv_pc',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='p_coupon_pv_sp',
            field=models.IntegerField(null=True, verbose_name='プレミアムクーポンPV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_drink_pv_pc',
            field=models.IntegerField(null=True, verbose_name='ドリンク写真_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_exterior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='外観写真_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_food_pv_pc',
            field=models.IntegerField(null=True, verbose_name='料理写真PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_info_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真詳細PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_interior_pv_pc',
            field=models.IntegerField(null=True, verbose_name='内観写真_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='photo_pv_sp',
            field=models.IntegerField(null=True, verbose_name='写真一覧PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='rating_pv_pc',
            field=models.IntegerField(null=True, verbose_name='口コミPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='rating_pv_sp',
            field=models.IntegerField(null=True, verbose_name='口コミPV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='seat_pv_pc',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='seat_pv_sp',
            field=models.IntegerField(null=True, verbose_name='座席情報PV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='top_pv_pc',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='top_pv_sp',
            field=models.IntegerField(null=True, verbose_name='店舗トップPV_sp'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='total_pv_pc',
            field=models.IntegerField(null=True, verbose_name='合計PV_pc'),
        ),
        migrations.AddField(
            model_name='wananakame_tb_scrape',
            name='total_pv_sp',
            field=models.IntegerField(null=True, verbose_name='合計PV_sp'),
        ),
    ]
